/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppGrid: typeof import('./components/Grids/AppGrid.vue')['default']
    AppointmentDetails: typeof import('./components/App/AppointmentDetails.vue')['default']
    Auth: typeof import('./components/Grids/Auth.vue')['default']
    BaseButton: typeof import('./components/App/BaseButton.vue')['default']
    BaseInput: typeof import('./components/App/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/App/BaseSelect.vue')['default']
    BoxDetail: typeof import('./components/App/BoxDetail.vue')['default']
    DoctorsGrid: typeof import('./components/App/doctorsGrid.vue')['default']
    Modal: typeof import('./components/App/Modal.vue')['default']
    Navigation: typeof import('./components/App/Navigation.vue')['default']
    OverlayLoader: typeof import('./components/App/OverlayLoader.vue')['default']
    ProfileDoctors: typeof import('./components/App/ProfileDoctors.vue')['default']
    Register: typeof import('./components/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
