/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./components/Grids/App.vue')['default']
    AppGrid: typeof import('./components/Grids/AppGrid.vue')['default']
    Auth: typeof import('./components/Grids/Auth.vue')['default']
    BaseButton: typeof import('./components/App/BaseButton.vue')['default']
    Navigation: typeof import('./components/App/Navigation.vue')['default']
    Register: typeof import('./components/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
